In [1]:
import numpy as np

In [2]:
M = np.random.randint(1,50)
N = np.random.randint(1,40)
a = np.random.randint(1, 100, size=(N, M))
a

array([[98, 45, 59, 64, 10, 54, 34, 53, 13, 95, 88, 37, 16, 22, 15, 30,
        91, 95, 46,  2],
       [53,  7, 88, 93, 81, 50, 96, 93, 21, 42, 31, 96, 87, 51, 70, 33,
        55, 50, 94, 92],
       [85, 47, 24, 36, 38, 95, 67, 49, 98, 78, 40, 15, 48, 28, 95, 33,
        30, 44, 29, 98],
       [26, 82, 43, 83, 72, 42, 75, 23, 87, 55, 43, 72, 69,  6,  5, 38,
        50, 23,  2, 83],
       [27, 38, 59, 61,  8, 61, 64, 47, 66, 57, 53, 74,  5, 68, 31, 85,
        63, 14, 54,  4],
       [ 6, 98, 42, 39, 86, 77, 62, 20, 73, 21, 81, 28, 25, 13, 14, 79,
        92, 61, 15, 47],
       [73, 13, 13, 31,  4, 51, 80,  6, 40, 29, 60, 40, 43, 18, 92, 12,
        92, 68, 68, 50],
       [89, 66, 54, 28, 52, 21, 51, 12, 80, 65, 51, 64, 70, 53, 86, 27,
        45, 69,  7, 44],
       [87, 92, 84, 44,  5,  3, 61, 40, 84, 79, 99, 48,  3, 86, 61, 84,
         8, 49, 49, 20],
       [15, 32, 24, 22, 52, 31, 58, 64, 72, 20, 83, 89,  3, 71, 34, 19,
        49, 52, 59, 15],
       [53, 75, 84, 69, 36, 92

In [3]:
a[2]

array([85, 47, 24, 36, 38, 95, 67, 49, 98, 78, 40, 15, 48, 28, 95, 33, 30,
       44, 29, 98])

In [4]:
a[:,2]

array([59, 88, 24, 43, 59, 42, 13, 54, 84, 24, 84, 40, 75, 79, 84, 15])

In [5]:
a[-1] = 7
a[-1]

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [6]:
a[:,-1] == np.sum(a[0] + a[1])
a[:,-1]

array([ 2, 92, 98, 83,  4, 47, 50, 44, 20, 15, 67, 10, 11, 65, 45,  7])